name: data_prep_ml
channels:
  - defaults
  - conda-forge
dependencies:
  - python == 3.9
  - pandas
  - isort
  - pytest
  - pre-commit
  - flake8
  - pip
  - pip:
    - blake
    - pandas
    - seaborn
    - git+https://github.com/hyperopt/hyperopt-sklearn


